version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Sincroniza el código fuente
    ports:
      - "8000:8000"
    depends_on:
      - db  # Asegúrate de que la base de datos esté disponible
