# Generated by Django 5.1.2 on 2024-11-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
    ]
